### ISSUE TITLE
Release with default pypi.org repository URL not working

### ISSUE THREAD

**Issue by d-ryan-ashcraft** [TechnologyBrewery/habushu#134]
When working with the default setup to push artifacts to the `pypi.org`, the following issue in encountered on push during the release workflow of 2.14.0:
```
Caused by: java.lang.NullPointerException
[INFO]     at org.technologybrewery.habushu.PublishToPyPiRepoMojo.addTrailingSlash (PublishToPyPiRepoMojo.java:231)
[INFO]     at org.technologybrewery.habushu.PublishToPyPiRepoMojo.getRepositoryUrl (PublishToPyPiRepoMojo.java:224)
[INFO]     at org.technologybrewery.habushu.PublishToPyPiRepoMojo.publishPackage (PublishToPyPiRepoMojo.java:162)
[INFO]     at org.technologybrewery.habushu.PublishToPyPiRepoMojo.doExecute (PublishToPyPiRepoMojo.java:122)
[INFO]     at org.technologybrewery.habushu.AbstractHabushuMojo.execute (AbstractHabushuMojo.java:304)
```

It appears that when using the default repo, we don't check that the url we want to ensure ends in a trailing slash is non-null before the the check.  

## Workaround
Can be worked around with the following configuration, if needed, in the meantime:
```xml
                <configuration>
                    <!--NB: workaround until https://github.com/TechnologyBrewery/habushu/issues/134 is fixed: -->
                    <pypiRepoUrl>https://pypi.org</pypiRepoUrl>
                </configuration>
```

**Comment by d-ryan-ashcraft** [comment]
Recreated with a new unit test:
```
[ERROR] Provides ability to push .dev versions to a different repository than released versions.Provides ability to push .dev versions to a different repository than released versions - Ensure trailing slash handles default case where an empty URL is passed to poetry for default handling without issue -- Time elapsed: 0.009 s <<< ERROR!
java.lang.NullPointerException
        at org.technologybrewery.habushu.PublishToPyPiRepoMojo.addTrailingSlash(PublishToPyPiRepoMojo.java:231)
        at org.technologybrewery.habushu.PublishToPyPiRepoMojo.getRepositoryUrl(PublishToPyPiRepoMojo.java:222)
        at org.technologybrewery.habushu.DeployPhaseSteps.the_repository_url_is_null(DeployPhaseSteps.java:51)
        at ✽.the repository url is null(classpath:specifications/dev-repository-deployment.feature:54)
```

**Comment by d-ryan-ashcraft** [comment]
Resolved
