### ISSUE TITLE
Python version being used in Habushu differs from configured version on Jenkins

### ISSUE THREAD

**Issue by d-ryan-ashcraft** [TechnologyBrewery/habushu#44]
When building with habushu, the it appears to be configured to use our target version of Python (3.11.4), but then fails in either the install-dependencies or format-python build phases because it is trying to use a different minor version of Python (3.9.16).

For example:
```
...
[INFO] --- habushu:2.7.0:validate-pyenv-and-poetry (default-validate-pyenv-and-poetry) @ habushu-mixology ---
[INFO] Executing pyenv command: pyenv versions --bare
[INFO] Executing pyenv command: pyenv local 3.11.4
[INFO] Using Python 3.11.4 (managed by pyenv)
[INFO] Found Poetry 1.2.2
[INFO] Configuring Poetry to use the pyenv-activated Python binary...
[INFO] Executing Poetry command: poetry config --local virtualenvs.prefer-active-python true
...
[INFO] --- habushu:2.7.0:format-python (default-format-python) @ habushu-mixology ---
[INFO] Executing Poetry command: poetry show black
[INFO] Formatting configured source and test directories using black...
[INFO] Executing Poetry command: poetry run black /home/jenkins/workspace/habuahu-test/habushu-mixology/src /home/jenkins/workspace/habuahu-test/habushu-mixology/tests
[ERROR] The currently activated Python version 3.9.16 is not supported by the project (^3.11).
Trying to find and use a compatible version. 
Traceback (most recent call last):
  File "/home/jenkins/.cache/pypoetry/virtualenvs/habushu-mixology-qQx63xOb-py3.9/bin/black", line 5, in <module>
    from black import patched_main
  File "src/black/__init__.py", line 38, in <module>
  File "src/black/comments.py", line 12, in <module>
  File "src/black/nodes.py", line 15, in <module>
ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by d-ryan-ashcraft** [comment]
### How to Fix
While this initially appears to be a habushu issue, it is actually a pyenv configuration issue. To solve this problem, you need to look at what your current version of pyenv does when `pyenv init -` is executed. At the time of this writing, it wants to have the following on the path:
```
/<path to pyenv>/.pyenv/shims:
```
Without this path, habushu is invoking the correct pyenv-based commands, but those commands don't actually activate the correct version of python without this shims content on the PATH.

With Jenkins, there is added challenged. While documentation appears to indicate that both `/etc/profile` and `/etc/bashrc` configuration should allow Jenkins to have the correct path, that does not work on current versions of Jenkins. Instead, you must configure you path via the Jenkins user interface:

1. Manage Jenkins
2. Configure System
3. Global Properties
4. Select Environment Variables (if not already active)
5. Update your PATH+EXTRA environment variable to start with the following:
`/<path to pyenv>/.pyenv/shims:/<path to pyenv>/.pyenv/bin:`

### But it Was Working Before...
You may not have noticed this issue before changing to a new minor version of Python. If your default Python version is, as in the example above, 3.9.16 and habushu is configured with anything else in the 3.9 release series, things will appear to work because Poetry's virtual environments are configured to include `<major>.<minor>` version numbers only (e.g., the `.cache/pypoetry/virtualenvs/habushu-mixology-qQx63xOb-py3.9` above). Things will line up and all will appear well. This is even true if you configure habushu with 3.10.x or 3.11.x and pyenv is not configured appropriately - you will notice it only when you set your `pyproject.toml` file to have a minimum that is not in the range of the default Python version (in the example above, the is 3.11).
